apiVersion: apps/v1
kind: Deployment
metadata:
  name: giftapp
  labels:
    app: giftapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: giftapp
  template:
    metadata:
      labels:
        app: giftapp
    spec:
      containers:
      - name: giftapp-container
        image: us.icr.io/sn-labs-brendonpilla/giftapp
        ports:
        - containerPort: 3060
        env:
        - name: MONGO_URL
          value: "mongodb://mongodb-service:27017"
        - name: JWT_SECRET
          value: "mysecret"
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
---
apiVersion: v1
kind: Service
metadata:
  name: gift-app-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3060
    protocol: TCP
  selector:
    app: giftapp
